# Source: kube-prometheus-stack/charts/grafana/templates/tests/test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ada-grafana-test
  labels:
    helm.sh/chart: grafana-6.26.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: ada
    app.kubernetes.io/version: "8.4.5"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
  namespace: monitoring
spec:
  serviceAccountName: ada-grafana-test
  containers:
    - name: ada-test
      image: "bats/bats:v1.4.1"
      imagePullPolicy: "IfNotPresent"
      command: ["/opt/bats/bin/bats", "-t", "/tests/run.sh"]
      volumeMounts:
        - mountPath: /tests
          name: tests
          readOnly: true
  volumes:
  - name: tests
    configMap:
      name: ada-grafana-test
  restartPolicy: Never
---