---
# Source: kube-prometheus-stack/charts/grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: grafana-6.26.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: ada
    app.kubernetes.io/version: "8.4.5"
    app.kubernetes.io/managed-by: Helm
  name: ada-grafana
  namespace: monitoring
---
# Source: kube-prometheus-stack/charts/grafana/templates/tests/test-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: grafana-6.26.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: ada
    app.kubernetes.io/version: "8.4.5"
    app.kubernetes.io/managed-by: Helm
  name: ada-grafana-test
  namespace: monitoring
---