---
# Source: kube-prometheus-stack/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ada-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.26.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: ada
    app.kubernetes.io/version: "8.4.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: 3000

  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: ada
---