apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonAnnotations:
  App: prometheus-operator-manifests

bases:
- ../../manifests/nfs
resources:
# -
# -
# patchesStratategicMerge:
# -
images:
- name: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0
  newTag: "v4.0.0"
  newName: cs0621/nfs-subdir-external-provisioner
