apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# generatorOptions:
#   disableNamesSuffixHash: ture
configMapGenerator:
- name: prometheus-configmap
  env: env.yaml
resources:
- crd.yaml
- alertmanager.yaml
- clusterrole.yaml
- deamonset.yaml
- deployment.yaml
- job.yaml
- sc.yaml
- prometheus.yaml
- prometheusrule.yaml
- secrets.yaml
- service-monitor.yaml
- service.yaml
vars:
- name: __APP_NAME__
  objref:
    kind: ConfigMap
    name: prometheus-configmap
    apiVersion: v1
  fieldref:
    fieldpath: data.__APP_NAME__

configurations:
- params.yaml